import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'


const frontendClient = axios.create({ baseURL: '/api'})


const Home: NextPage = () => {
  const [players, setPlayers] = useState([])

  useEffect(() => {
    async function load() {
      console.log('aaaaaaa')
      const response = await frontendClient.get('/csgo')
      console.log(response)

      console.log(response.data)

      setPlayers(response.data)
    }
    load()
  }, [])
  
  const sortByRanking = (a: any, b: any) => Number(b.ranking) - Number(a.ranking)
  const sortByWins = (a: any, b: any) => Number(b.wins) - Number(a.wins)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>NatusLactare</h1>

        <table className={styles.table}>
          <thead>
            <tr className={styles.text}>
              <th>Ranking</th>
              <th>Jogador</th>
              <th>Vitórias</th>
            </tr>
          </thead>
          <tbody>
            {players.sort(sortByWins).sort(sortByRanking).map((player: any) => (
              <tr key={player.id} className={styles.text}>
                <td>
                  {typeof player.rankingImage === 'string' && player.rankingImage !== '' && <Image src={player.rankingImage} width={92} height={36.61} alt="ranking"></Image>}
                </td>
                <td>{player.name}</td>
                <td>{player.wins}</td>
                <td><a href={player.playerURL} target="_blank" rel="noreferrer">go to <span>csgo<span>stats</span>.gg</span></a></td>
              </tr>
            ))
            }
          </tbody>
        </table>
      </main>

      <footer className={styles.footer}>
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
